### ISSUE TITLE
require("Ractive") should be lowercase

### ISSUE THREAD

**Issue by lucasmotta** [1N50MN14/Ractive-transitions-scale#3]
Since version 0.4.0, all the file names should be in lowercase: `require("Ractive")` now should be:
```
require("ractive");
```

I would also recommend making the name of this transition lowercase to match this change and the other transitions.

**Comment by timshannon** [comment]
Just ran into this same issue.

**Comment by 1N50MN14** [comment]
Hey guys, apologies for the (very) late response (work & children!); will update this over the weekend otherwise if you want this earlier please feel free to send a PR and I'll merge it  ;)

**Comment by timshannon** [comment]
No rush, the fix is simple.  Pull it at your leisure.
