### ISSUE TITLE
Add bower.json/component.json and register this component

### ISSUE THREAD

**Issue by lucasmotta** [1N50MN14/Ractive-transitions-scale#4]

**Comment by wmcmurray** [comment]
this pull request : https://github.com/1N50MN14/Ractive-transitions-scale/pull/6 intend to fix this !

**Comment by 1N50MN14** [comment]
closed via #6

**Comment by wmcmurray** [comment]
Also, I just registered this component via bower so you can `bower install ractive-transitions-scale` !

**Comment by 1N50MN14** [comment]
Sounds great! I'm not familiar with bower (more of an npm kind of guy) but I'm sure this would help others, thanks again :)
